package numer0n;
import numer0n.service.impl.GameManagerImpl;

/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {

    public static void main(String[] args) {
        // ゲームを開始
        GameManagerImpl gameManager = new GameManagerImpl();
        gameManager.start();
    }
}
